name = "TVESim"
uuid = "e66252d3-0630-4220-9d11-0d589aee9c8a"
authors = ["Rufat Badal <tours-flashy-0j@icloud.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
